---
title: "ETS Models"
output: 
  html_document: 
    keep_md: yes
---

Import necessary libraries
```{r}
library(RCurl)
library(gdata)
library(forecast)
library(tseries)
library(ggplot2)
```

Load bookings dataset
```{r}
destfile <- "input/bookings.csv"

if(!file.exists(destfile)){
  download.file("http://video.udacity-data.com.s3.amazonaws.com/topher/2016/September/57e94998_bookings.csv/bookings.csv.xlsx",destfile=destfile,method="libcurl")
}

bookings_df <- read.csv(file = destfile, header=TRUE)
```

```{r}
bookings_ts <- ts(data=bookings_df$Bookings, start=2006, frequency=12)
```

Time series decomposition
```{r}
bookings_ts_dec <- decompose(bookings_ts)
plot(bookings_ts_dec)
```

```{r}
bookings_model <- ets(y=bookings_ts)
bookings_fcast <- forecast(bookings_model, h=10*12)
plot(bookings_fcast)
```

Load champagne sales dataset
```{r}
destfile <- "input/champagne-sales.xlsx"

if(!file.exists(destfile)){
  download.file("http://video.udacity-data.com.s3.amazonaws.com/topher/2016/September/57cefe8e_champagne-sales/champagne-sales.xlsx",destfile=destfile,method="libcurl")
}

champ_df <- read.xls (xls = destfile, sheet = 1, header = TRUE)
```

```{r}
champ_ts <- ts(data=champ_df$Champagne.Sales, start=2001, frequency=12)
```

https://anomaly.io/seasonal-trend-decomposition-in-r/
https://a-little-book-of-r-for-time-series.readthedocs.io/en/latest/src/timeseries.html

```{r}
plot.ts(champ_ts)
```

Time series decomposition
```{r}
plot(decompose(x=bookings_ts))
```

```{r}
champ_model <- ets(y=champ_ts)
champ_fcast <- forecast(champ_model, h=10*12)
plot(champ_fcast)
```

Build an ETS(M,N,M) model. Use the last 6 periods as a holdout or validation sample, and forecast 6 periods. 
```{r}
champ_ts <- ts(data=head(champ_df$Champagne.Sales, -6), start=2001, frequency=12)
champ_model <- ets(y=champ_ts, model="MNM")
champ_fcast <- forecast(champ_model, h=6)
plot(champ_fcast)
```

```{r}
window(champ_fcast$mean, start=2001, frequency=12)
```

