---
title: "Single Exponential Smoothing"
output: 
  html_document: 
    keep_md: yes
---

Import necessary libraries
```{r}
library(RCurl)
library(gdata)
library(forecast)
library(tseries)
library(ggplot2)
```

Load single home family sales dataset
```{r}
destfile <- "input/single-family-home-sales.xlsx"

if(!file.exists(destfile)){
  download.file("http://video.udacity-data.com.s3.amazonaws.com/topher/2016/September/57e47a41_single-family-home-sales/single-family-home-sales.xlsx",destfile=destfile,method="libcurl")
}

sfh_sales <- read.xls (xls = destfile, sheet = 1, header = TRUE)
```

Feature engineering
```{r}
sfh_sales$Month <- as.Date(paste0(sfh_sales$Month, "-01"), format = "%Y-%m-%d")
```

```{r}
sfh_sales_ts <- ts(data=sfh_sales$Home.Sales, start=1990, frequency=12)
```

```{r}
plot.ts(sfh_sales_ts)
```

```{r}
sfh_sales$Home.Sales.Clean <- tsclean(ts(sfh_sales$Home.Sales))
ggplot(data=sfh_sales, aes(x=Month, y=Home.Sales.Clean)) + geom_line()
```

Time series decomposition
```{r}
plot(decompose(sfh_sales_ts))
```

Using a smoothing parameter (α) of 0.8, what is the forecast for December 2015?
```{r}
sfh_sales_ses <- ets(y=sfh_sales_ts, model="ZNN", alpha=0.8)
sfh_sales_ses_fcast <- forecast(sfh_sales_ses, h=20*12)
window(sfh_sales_ses_fcast$mean, start=2015, frequency=12)
```

Using a smoothing parameter (α) of 0.6, what is the forecast for December 2015?
```{r}
sfh_sales_ses <- ets(y=sfh_sales_ts, model="ZNN", alpha=0.6)
sfh_sales_ses_fcast <- forecast(sfh_sales_ses, h=20*12)
window(sfh_sales_ses_fcast$mean, start=2015, frequency=12)
```

Using a smoothing parameter (α) of 0.2, what is the forecast for December 2015?
```{r}
sfh_sales_ses <- ets(y=sfh_sales_ts, model="ZNN", alpha=0.2)
sfh_sales_ses_fcast <- forecast(sfh_sales_ses, h=20*12)
window(sfh_sales_ses_fcast$mean, start=2015, frequency=12)
```